# Library & Data import

In [7]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

In [8]:
df = pd.read_csv('..\Data\\Organized_data_1_0.csv', low_memory=False)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Idan\AppData\Local\Temp\ipykernel_33444\1082348874.py:1: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv('..\Data\\Organized_data_1_0.csv', low_memory=False)

In [9]:
pd.set_option('display.max_rows', 200)  # In case rows are being cut off too

# First look at the data

In [10]:
# Dataset shape
print("There are {} rows and {} columns in the dataset".format(df.shape[0], df.shape[1]))

There are 3645995 rows and 8 columns in the dataset

In [11]:
# Quick look into the first 5 rows of the dataset
df.head()

,City,Incident Zip,Agency,Location Type,Status,Location,Resolution Time,Complaint_Type
0,WOODSIDE,11377,NYPD,Street/Sidewalk,Closed,POINT (-73.907196579197 40.743018746122),0 days 02:14:24,Vehicles & Parking
1,FAR ROCKAWAY,11694,HPD,RESIDENTIAL BUILDING,Closed,POINT (-73.839021963252 40.577671995863),2 days 16:48:36,Housing & Building Maintenance
2,NEW YORK,10033,HPD,RESIDENTIAL BUILDING,Closed,POINT (-73.937239002314 40.851013911318),2 days 09:37:04,Housing & Building Maintenance
3,BROOKLYN,11207,HPD,RESIDENTIAL BUILDING,Closed,POINT (-73.899924654626 40.663886523056),2 days 13:19:51,Housing & Building Maintenance
4,BROOKLYN,11234,DSNY,Street,Closed,POINT (-73.912414463066 40.625294042041),0 days 07:02:00,Vehicles & Parking

In [12]:
# See each column and its data type
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3645995 entries, 0 to 3645994
Data columns (total 8 columns):
 #   Column           Dtype
---  ------           -----
 0   City             str
 1   Incident Zip     str
 2   Agency           str
 3   Location Type    str
 4   Status           str
 5   Location         str
 6   Resolution Time  str
 7   Complaint_Type   str
dtypes: str(8)
memory usage: 222.5 MB

In [14]:
# Lets see the problems people complain about
print(df["Complaint_Type"].unique())

<StringArray>
[            'Vehicles & Parking', 'Housing & Building Maintenance',
                          'Noise',             'Sanitation & Trash',
        'Street & Infrastructure',          'Public Order & Police',
  'Health & Environmental Safety',                     'Other/Misc',
                  'Trees & Parks',             'Construction & DOB',
       'Taxi & For-Hire Vehicles',                 'Animals & Pets']
Length: 12, dtype: str

In [16]:
df["Complaint_Type"].value_counts()

Complaint_Type
Vehicles & Parking                877554
Noise                             831176
Housing & Building Maintenance    786282
Street & Infrastructure           229255
Sanitation & Trash                224815
Public Order & Police             179686
Other/Misc                        177515
Health & Environmental Safety     141139
Trees & Parks                      71259
Construction & DOB                 63241
Animals & Pets                     34471
Taxi & For-Hire Vehicles           29602
Name: count, dtype: int64

In [ ]:
# Check if there are duplicates
print(df.duplicated().sum())

363809

In [21]:
# Show all duplicate rows (keeps ALL occurrences, including the first)
duplicates = df[df.duplicated(keep=False)]
print(f"Total duplicate rows: {len(duplicates)}")
duplicates

Total duplicate rows: 515813

,City,Incident Zip,Agency,Location Type,Status,Location,Resolution Time,Complaint_Type
51,NEW YORK,10075,HPD,RESIDENTIAL BUILDING,Closed,POINT (-73.957188128108 40.772507525524),59 days 05:43:42,Housing & Building Maintenance
52,NEW YORK,10075,HPD,RESIDENTIAL BUILDING,Closed,POINT (-73.957188128108 40.772507525524),59 days 05:43:42,Housing & Building Maintenance
53,NEW YORK,10075,HPD,RESIDENTIAL BUILDING,Closed,POINT (-73.957188128108 40.772507525524),59 days 05:43:42,Housing & Building Maintenance
125,NEW YORK,10030,NYPD,Street/Sidewalk,Closed,POINT (-73.941355796357 40.81853515725),0 days 00:35:55,Noise
169,BROOKLYN,11226,HPD,RESIDENTIAL BUILDING,Closed,POINT (-73.95992971344 40.644328077072),17 days 16:10:10,Housing & Building Maintenance
...,...,...,...,...,...,...,...,...
3645753,BROOKLYN,11239,NYPD,Street/Sidewalk,Closed,POINT (-73.873239856683 40.654753023817),0 days 00:08:54,Vehicles & Parking
3645823,BRONX,10456,NYPD,Residential Building/House,Closed,POINT (-73.903744412981 40.836940662924),0 days 00:13:55,Noise
3645838,NEW YORK,10013,NYPD,Residential Building/House,Closed,POINT (-74.006742504023 40.720222323433),0 days 00:03:44,Noise
3645847,BRONX,10456,NYPD,Residential Building/House,Closed,POINT (-73.903744412981 40.836940662924),0 days 00:14:49,Noise
3645932,NEW YORK,10013,NYPD,Residential Building/House,Closed,POINT (-74.006742504023 40.720222323433),0 days 00:01:24,Noise

# Missing Values

In [18]:
# Number of missing value for each feature.
df.isnull().sum()

City               155664
Incident Zip        29813
Agency                  0
Location Type      429725
Status                  0
Location            50024
Resolution Time     72269
Complaint_Type          0
dtype: int64

In [19]:
# Percentage of missing values for each feature.
df.isnull().mean()*100

City                4.269452
Incident Zip        0.817692
Agency              0.000000
Location Type      11.786220
Status              0.000000
Location            1.372026
Resolution Time     1.982148
Complaint_Type      0.000000
dtype: float64

This is the data which is Null/None/NaN... But what if the missing data was written as Unknown or Unavailable? Let's check

As we can see, most of the columns have missing values. We will decide on how to deal with them later on.